spring:
  cloud:
    config:
      enabled: false
  session:
    jdbc:
      initialize-schema: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 195192037893-34d1201fp2sujorfbb26ufo8vj8e730g.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: 'http://localhost:8080/security/oauth2/callback'
            scope:
              - openid
              - email
gemini:
  key: AIzaSyDXldaAlDkKOvpbxqMjkyNkSQyE1BFG08g

custom:
  datasource:
    url: jdbc:postgresql://localhost:5432/waifudb
    username: wapi_root
    password: password
#
#server:
#  ssl:
#    key-store: classpath:springboot.p12
#    key-store-password: password
#    key-store-type: pkcs12
#    key-alias: springboot
#    key-password: password
#  port: 8443