spring:
  cloud:
    config:
      enabled: false
  session:
    jdbc:
      initialize-schema: always

gemini:
  key: AIzaSyDXldaAlDkKOvpbxqMjkyNkSQyE1BFG08g

custom:
  datasource:
    url: jdbc:postgresql://localhost:5432/waifudb
    username: postgres
    password: password
#
#server:
#  ssl:
#    key-store: classpath:springboot.p12
#    key-store-password: password
#    key-store-type: pkcs12
#    key-alias: springboot
#    key-password: password
#  port: 8443